version: "1"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:8002
  volumes:
    - /data/jenkins_home/workspace/components_master/nginx.conf:/etc/nginx/conf.d/default.conf
    - /data/jenkins_home/workspace/components_master/build:/usr/share/nginx/html
  command: /bin/bash -c "nginx -g 'daemon off;'"
