version: "3"
services:
  jenkins-ci:
    user: root
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /data/jenkins_home:/var/jenkins_home
      - /data/nm_cache:/var/nm_cache
      - /var/run/docker.sock:/var/run/docker.sock
